#!/bin/sh
# # x-sed -- POSIX sed on x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower, the
#   required grep bundle, then SED, with no launcher.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# THE REQUIRED LANGS, READ FROM THE MANIFEST (the x-r7rs pattern): x.sh
# resolves (requires-lang ...) itself; the harness repeats the
# resolution from the same rows.  Both layouts are probed -- an install
# names the directory after the lang, a checkout after the repository.
# The version, when the row grows one, is deliberately ignored here:
# this harness exists to run against working trees.
DEP_ROOTS=
for _req in $(sed -n 's/^(requires-lang "\([^"]*\)".*/\1/p' "$BUNDLE/lang.xon"); do
	_root=
	for _c in "$BUNDLE/../$_req" "$BUNDLE/../x-$_req"; do
		if [ -f "$_c/lang.xon" ]; then _root="$(cd "$_c" && pwd)"; break; fi
	done
	if [ -z "$_root" ]; then
		echo "x-sed: lang '$_req' is required but not beside this bundle" >&2
		echo "  looked for $_req/ and x-$_req/ next to $BUNDLE" >&2
		exit 1
	fi
	DEP_ROOTS="$DEP_ROOTS $_root"
done

DEP_FORMS=
for _d in $DEP_ROOTS; do
	DEP_FORMS="$DEP_FORMS(import-path! \"$_d\")
"
done

# The launcher-free boot amalgam; see x-awk's notes.
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-sed: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
$DEP_FORMS(import-path! "$BUNDLE")
(import sed/base)
(set! %repl-print %sed-repl-print)
EOF
